import { awscdk } from 'projen';
import * as fs from 'fs';
import * as yaml from 'yaml';

const project = new awscdk.AwsCdkConstructLibrary({
  name: 'simple-agentcore-runtime-patterns',
  description:
    'AWS CDK construct library for deploying Bedrock AgentCore Runtime',
  author: '@ivorycirrus',
  authorAddress: 'ivorycirrus@gmail.com',
  repositoryUrl:
    'https://github.com/ivorycirrus/simple-agentcore-construct.git',
  licensed: true,
  license: 'MIT-0',
  copyrightOwner: '@ivorycirrus',
  copyrightPeriod: '2025',

  // Project Configs
  projenrcTs: true,
  cdkVersion: '2.221.0',
  jsiiVersion: '~5.9.0',
  deps: [
    'cdk-nag',
    'cdk-ecr-deployment',
    '@aws-cdk/aws-lambda-python-alpha',
  ],
  devDeps: ['esbuild', 'yaml'],

  // Packing Options
  packageName: 'simple-agentcore-runtime-patterns',
  publishToPypi: {
    distName: 'simple-agentcore-runtime-patterns',
    module: 'simple_agentcore_runtime_patterns',
  },

  // Release options
  defaultReleaseBranch: 'release',
  buildWorkflowOptions: { mutableBuild: false }, // Disable self-mutation in build workflow
  depsUpgrade: false, // Disable automatic dependency upgrades
  mergify: false, // Disable mergify
  npmignore: ['AGENTS.md'], // Exclude AGENTS.md from package
  bundledDeps: [],
  gitignore: ['build/'],
});

// ESLint Rules
project.eslint?.addRules({
  '@typescript-eslint/no-unused-vars': [
    'error',
    {
      argsIgnorePattern: '^_',
      varsIgnorePattern: '^_',
    },
  ],
});

project.compileTask.prependExec('ts-node --project tsconfig.dev.json scripts/bundle-lambda-agentcore-runtime-lambda-url-streaming.ts');

// Add QEMU and Docker Buildx setup to GitHub Actions workflows for ARM64 support
project.postSynthesize = () => {
  const dockerSetupSteps = [
    {
      name: 'Set up QEMU',
      uses: 'docker/setup-qemu-action@v3',
    },
    {
      name: 'Set up Docker Buildx',
      uses: 'docker/setup-buildx-action@v3',
    },
  ];

  const workflowFiles = [
    '.github/workflows/release.yml',
    '.github/workflows/build.yml',
  ];

  for (const workflowFile of workflowFiles) {
    try {
      // Make file writable
      try {
        fs.chmodSync(workflowFile, 0o644);
      } catch (e) {
        // Ignore if file doesn't exist yet
      }

      const content = fs.readFileSync(workflowFile, 'utf8');
      const workflow = yaml.parse(content);

      // Find jobs that have 'Install dependencies' step
      for (const jobName of Object.keys(workflow.jobs || {})) {
        const job = workflow.jobs[jobName];
        if (job.steps && Array.isArray(job.steps)) {
          const installDepsIndex = job.steps.findIndex(
            (step: any) => step.name === 'Install dependencies'
          );
          if (installDepsIndex >= 0) {
            // Check if QEMU setup already exists
            const hasQemu = job.steps.some((step: any) => step.name === 'Set up QEMU');
            if (!hasQemu) {
              // Insert Docker setup steps before Install dependencies
              job.steps.splice(installDepsIndex, 0, ...dockerSetupSteps);
            }
          }
        }
      }

      // Write back with projen header
      const header = '# ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".\n\n';
      fs.writeFileSync(workflowFile, header + yaml.stringify(workflow), { mode: 0o444 });
    } catch (error) {
      console.warn(`Failed to update ${workflowFile}:`, error);
    }
  }
};

project.synth();
